export const products = [
  { id: 'butter', group: 'classics', name: { uk: 'Круасан на маслі', en: 'All-butter croissant', fr: 'Croissant pur beurre' }, description: { uk: 'Тридцять два шари терпіння, французьке масло й хрускіт, який чути на весь ранок.', en: 'Thirty-two layers of patience, French butter and a morning-worthy crunch.', fr: 'Trente-deux couches de patience, du beurre français et un joli croustillant.' }, price: 105, image: 'photo-1555507036-ab1f4038808a' },
  { id: 'pain-choc', group: 'classics', name: { uk: 'Пан-о-шоколя', en: 'Pain au chocolat', fr: 'Pain au chocolat' }, description: { uk: 'Два бруски темного шоколаду заховалися між тонкими масляними шарами.', en: 'Two batons of dark chocolate tucked between delicate buttery layers.', fr: 'Deux bâtons de chocolat noir glissés entre de fines couches beurrées.' }, price: 125, image: 'photo-1623334044303-241021148842' },
  { id: 'almond', group: 'classics', name: { uk: 'Мигдалевий круасан', en: 'Almond croissant', fr: 'Croissant aux amandes' }, description: { uk: 'Круасан із франжипаном та мигдалевими пелюстками.', en: 'Croissant with frangipane and toasted almond flakes.', fr: 'Croissant à la frangipane et aux amandes effilées.' }, price: 145, image: 'photo-1623334044303-241021148842' },
  { id: 'pistachio', group: 'filled', name: { uk: 'Фісташковий вузлик', en: 'Pistachio knot', fr: 'Nœud à la pistache' }, description: { uk: 'Фісташкова паста власного приготування і трохи морської солі.', en: 'House-made pistachio paste and a pinch of sea salt.', fr: 'Pâte de pistache maison et une pincée de sel.' }, price: 175, image: 'photo-1555507036-ab1f4038808a' },
  { id: 'berry', group: 'filled', name: { uk: 'Даніш із сезонними ягодами', en: 'Seasonal berry danish', fr: 'Danoise aux fruits de saison' }, description: { uk: 'Ванільний крем і ягоди, що сьогодні пахнуть найкраще.', en: 'Vanilla cream and whichever berries smell best today.', fr: 'Crème vanillée et les fruits qui sentent le meilleur aujourd’hui.' }, price: 155, image: 'photo-1509365465985-25d11c17e812' },
  { id: 'cinnamon', group: 'filled', name: { uk: 'Равлик із кардамоном', en: 'Cardamom morning bun', fr: 'Escargot à la cardamome' }, description: { uk: 'Кориця, зелений кардамон і трохи карамелізованого цукру.', en: 'Cinnamon, green cardamom and caramelised sugar at the edges.', fr: 'Cannelle, cardamome verte et sucre délicieusement caramélisé.' }, price: 120, image: 'photo-1509365465985-25d11c17e812' },
  { id: 'quiche', group: 'savory', name: { uk: 'Кіш із цибулею та козячим сиром', en: 'Onion & goat cheese quiche', fr: 'Quiche oignons et chèvre' }, description: { uk: 'Повільно томлена цибуля, козячий сир і хрустке тісто.', en: 'Slow-cooked onions, goat cheese and our crisp pastry shell.', fr: 'Oignons confits, chèvre doux et pâte croustillante.' }, price: 190, image: 'photo-1578985545062-69928b1d9587' },
  { id: 'coffee', group: 'small', name: { uk: 'Капучино', en: 'Cappuccino', fr: 'Cappuccino' }, description: { uk: 'Подвійний еспресо, молоко та піна, що тримає маленьке серце.', en: 'Double espresso, steamed milk and a little heart in the foam.', fr: 'Double espresso, lait chaud et mousse en forme de cœur.' }, price: 95, image: 'photo-1509042239860-f550ce710b93' },
  { id: 'juice', group: 'small', name: { uk: 'Сік із яблук і груш', en: 'Apple & pear juice', fr: 'Jus pomme et poire' }, description: { uk: 'Свіжий сік із яблук та груш від сусіднього саду.', en: 'Fresh-pressed apples and pears from a neighbouring orchard.', fr: 'Pommes et poires fraîchement pressées du verger voisin.' }, price: 85, image: 'photo-1621506289937-a8e4df240d0b' },
]

export const locations = [
  ['Lviv', 'ukraine', 'пл. Ринок, 12', '12 Rynok Square', '12, place du Marché', '08:00–20:00', 'cafe'],
  ['Lviv', 'ukraine', 'вул. Личаківська, 8', '8 Lychakivska Street', '8, rue Lytchakivska', '07:30–16:00', 'counter'],
  ['Kyiv', 'ukraine', 'вул. Ярославів Вал, 21', '21 Yaroslaviv Val Street', '21, rue Yaroslaviv Val', '08:00–21:00', 'cafe'],
  ['Kyiv', 'ukraine', 'вул. Січових Стрільців, 15', '15 Sichovykh Striltsiv Street', '15, rue Sichovykh Striltsiv', '08:00–16:00', 'counter'],
  ['Odesa', 'ukraine', 'вул. Грецька, 34', '34 Hretska Street', '34, rue Hretska', '08:00–20:00', 'cafe'],
  ['Dnipro', 'ukraine', 'просп. Дмитра Яворницького, 18', '18 Dmytro Yavornytskyi Avenue', '18, avenue Dmytro Yavornytskyi', '08:00–16:00', 'counter'],
  ['Warsaw', 'poland', 'вул. Мокотовська, 28', '28 Mokotowska Street', '28, rue Mokotowska', '08:00–20:00', 'cafe'],
  ['Warsaw', 'poland', 'вул. Хмельна, 7', '7 Chmielna Street', '7, rue Chmielna', '07:30–16:00', 'counter'],
  ['Kraków', 'poland', 'вул. Флоріанська, 42', '42 Floriańska Street', '42, rue Floriańska', '08:00–20:00', 'cafe'],
  ['Wrocław', 'poland', 'вул. Свідницька, 9', '9 Świdnicka Street', '9, rue Świdnicka', '08:00–16:00', 'counter'],
  ['Paris', 'france', 'вул. Розьє, 15', '15 Rue des Rosiers', '15, rue des Rosiers', '08:00–20:00', 'cafe'],
  ['Paris', 'france', 'вул. Бретань, 33', '33 Rue de Bretagne', '33, rue de Bretagne', '07:30–16:00', 'counter'],
  ['Lyon', 'france', 'вул. Мерсьєр, 26', '26 Rue Mercière', '26, rue Mercière', '08:00–20:00', 'cafe'],
  ['Bordeaux', 'france', 'вул. Сент-Катрін, 61', '61 Rue Sainte-Catherine', '61, rue Sainte-Catherine', '08:00–16:00', 'counter'],
].map(([city, country, addressUk, addressEn, addressFr, hours, format], index) => ({
  id: index + 1, city, country, address: { uk: addressUk, en: addressEn, fr: addressFr }, hours, format,
  countryName: { uk: country === 'ukraine' ? 'Україна' : country === 'poland' ? 'Польща' : 'Франція', en: country === 'ukraine' ? 'Ukraine' : country === 'poland' ? 'Poland' : 'France', fr: country === 'ukraine' ? 'Ukraine' : country === 'poland' ? 'Pologne' : 'France' },
}))

export const articles = [
  { slug: 'layers-of-time', category: { uk: 'З нашої кухні', en: 'From our kitchen', fr: 'De notre cuisine' }, title: { uk: 'Чому ми складаємо тісто саме тридцять два рази', en: 'Why we fold the dough thirty-two times', fr: 'Pourquoi plions-nous la pâte trente-deux fois ?' }, excerpt: { uk: 'Трохи про ламінування, довгі ночі й ту саму хрустку крихту.', en: 'A little about lamination, long nights and that crisp first bite.', fr: 'Un peu de feuilletage, de longues nuits et de ce premier croustillant.' }, date: '14.05.2025', minutes: 5, image: 'photo-1555507036-ab1f4038808a', body: { uk: 'Між маслом і борошном є тиша. Саме в ній народжуються шари. Ми починаємо, коли вулиці вже темні, і складаємо, розкачуємо, чекаємо — ще раз і ще.\n\nКоли круасан нарешті виходить із печі, кожен шар пам’ятає про терпіння. І коли крихти лишаються на вашій серветці, нам здається, що ніч була недаремною.', en: 'There is a quiet space between butter and flour. That is where the layers begin. We start when the streets are dark, then fold, roll and wait — again and again.\n\nWhen a croissant finally comes out of the oven, every layer remembers the patience it took. And when crumbs land on your napkin, we know the night was worth it.', fr: 'Entre le beurre et la farine, il y a un silence. C’est là que naissent les couches. Nous commençons quand les rues sont sombres : plier, étaler, attendre, encore.\n\nQuand le croissant sort du four, chaque couche se souvient de la patience. Quelques miettes sur votre serviette, et la nuit en valait la peine.' } },
  { slug: 'butter-notebook', category: { uk: 'Інгредієнти', en: 'Ingredients', fr: 'Ingrédients' }, title: { uk: 'Про масло, яке тримає обіцянку', en: 'On the butter that keeps its promise', fr: 'Du beurre qui tient sa promesse' }, excerpt: { uk: 'Знайомимось із найважливішим мешканцем нашої холодильної полиці.', en: 'Meet the most important resident of our fridge shelf.', fr: 'Rencontre avec le plus important habitant de notre réfrigérateur.' }, date: '02.04.2025', minutes: 4, image: 'photo-1550583724-b2692b85b150', body: { uk: 'Масло має бути холодним, пластичним і пахнути вершками. Від нього залежить характер кожного шару.\n\nМи куштуємо його окремо, перш ніж познайомити з борошном. Бо гарний круасан починається з дуже маленьких деталей.', en: 'Butter should be cold, pliable and smell like cream. Every layer depends on its character.\n\nWe taste it on its own before introducing it to the flour. A good croissant begins with very small details.', fr: 'Le beurre doit être froid, souple et sentir la crème. Chaque couche dépend de son caractère.\n\nNous le goûtons seul avant de le présenter à la farine. Un bon croissant commence par de tout petits détails.' } },
  { slug: 'first-coffee', category: { uk: 'Малі ритуали', en: 'Little rituals', fr: 'Petits rituels' }, title: { uk: 'Перша кава — ще до того, як прокинеться місто', en: 'The first coffee, before the city wakes', fr: 'Le premier café, avant le réveil de la ville' }, excerpt: { uk: 'Коротка історія про ранкові зміни та перше світло у вікні.', en: 'A short story about early shifts and the first light in the window.', fr: 'Une petite histoire de service matinal et de première lumière.' }, date: '18.03.2025', minutes: 3, image: 'photo-1445116572660-236099ec97a0', body: { uk: 'Перша кава — це не зовсім кава. Це спосіб сказати одне одному «доброго ранку», поки слова ще не встигли прокинутись.\n\nПотім приходять перші гості, сонце торкається підвіконня, і день складається у щось хороше.', en: 'The first coffee isn’t quite coffee yet. It is a way of saying good morning before words have properly woken up.\n\nThen come the first guests, the sun reaches the windowsill, and the day starts to feel lovely.', fr: 'Le premier café n’est pas tout à fait un café. C’est une façon de se dire bonjour avant que les mots ne se réveillent.\n\nPuis arrivent les premiers clients, le soleil touche le rebord de la fenêtre, et la journée prend une jolie tournure.' } },
]