export const copy = {
  uk: {
    nav: { home: 'Головна', menu: 'Меню', places: 'Локації', story: 'Наша історія', journal: 'Журнал', contact: 'Контакти', order: 'Замовити', reserve: 'Забронювати столик' },
    common: { since: 'З любов’ю з 2016', handmade: 'Зроблено руками, не поспіхом', viewAll: 'Дивитися всі', read: 'Читати історію', from: 'від', add: 'Додати', added: 'Додано', address: 'Адреса', hours: 'Години', cafe: 'Кафе', counter: 'З собою', reserve: 'Забронювати', order: 'Замовити', all: 'Усі', ukraine: 'Україна', poland: 'Польща', france: 'Франція', back: 'Назад', quantity: 'Кількість', total: 'Разом', cart: 'Ваш кошик', empty: 'Поки що тут пахне лише планами.', close: 'Закрити', placeholder: 'Демонстраційні дані макета. Адреси й деталі потрібно підтвердити перед запуском.' },
    home: { eyebrow: 'Пекарня маленьких бажань · Львів, з 2016', title: 'Деякі ранки\nстворені для\nще теплого круасана.', intro: 'Ми віримо, що хороші речі не поспішають. Тісто відпочиває, масло тане між шарами, а місто поволі прокидається.', story: 'Так починалася наша історія', discover: 'Смакувати меню', featured: 'Те, заради чого\nварто прокинутись', note: 'Розгорніть серветку. Ранок уже тут.', locationsTitle: 'Трохи ближче, ніж здається', locationsText: 'Від маленької львівської пекарні до столиків у Парижі й Варшаві — у кожному місті ми залишаємо місце для повільного ранку.', journalTitle: 'Нотатки з нашої кухні', journalText: 'Історії, запахи й рецепти, якими хочеться ділитися.', quote: '«Секрет не в поспіху. Секрет — у ще одному шарі масла.»', quoteBy: 'Із блокнота нашої засновниці', cta: 'Знайти свій ранковий столик' },
    menu: { eyebrow: 'З нашої печі · щодня зранку', title: 'Усе найкраще —\nміж шарами.', intro: 'Листкове тісто любить терпіння. Ми даємо йому цілу ніч, а вам — привід не поспішати з вибором.', classics: 'Класика з маслом', filled: 'Трохи більше начинки', savory: 'Несолодкий ранок', small: 'До круасана', note: 'Маленькі партії. Коли закінчується — завтра буде свіже.', orderNote: 'Онлайн-замовлення демонстраційне; оплату поки не підключено.' },
    places: { eyebrow: 'Завітайте на хвильку або залишайтесь', title: 'Ми вже\nрозклали серветки.', intro: 'Чотирнадцять місць, де можна зупинитися на каву й щось щойно з печі. Деякі з них — лише віконце й запах масла, інші — повільний сніданок за столом.', cafe: 'Кафе зі столиками', counter: 'Пекарня з собою', filter: 'Шукати за країною', map: 'Наші міста', reserveNote: 'Бронювання доступне лише у кафе зі столиками.' },
    about: { eyebrow: 'Notre histoire · наша історія', title: 'Один рецепт.\nЦіла низка ранків.', intro: 'Усе почалося з рецепта, який повернувся додому в кишені фартуха. Із Парижа — до кухні у Львові, де ми навчилися чекати на тісто.', quote: '«Мама казала: якщо є час на ще один шар, значить, він потрібен.»', storyTitle: 'Кишеньковий рецепт', p1: 'У 2016 році наша родинна історія пахла маслом, яке повільно вбирається в борошно. Рецепт приїхав із паризького стажування — трохи пом’ятий, записаний олівцем, але вже тоді безпомилково наш.', p2: 'Першу пекарню ми відчинили у Львові. На світанку розкачували тісто, а до обіду вчилися вимовляти імена людей, які поверталися по ще один круасан. Відтоді змінилося багато міст, та не цей ранковий ритуал.', p3: 'Тепер у нас є чотирнадцять дверей у трьох країнах — від маленьких віконець на виніс до кафе, де можна залишитися на сніданок. Усі цифри й адреси тут поки що макетні; сам рецепт усе ще починається з терпіння.', timelineTitle: 'Сторінки календаря', t1: 'Рецепт повертається з Парижа', t2: 'Відчиняємо першу пекарню у Львові', t3: 'Наші ранки з’являються у Варшаві', t4: 'Ще кілька столиків — уже в Парижі', end: 'Дякуємо, що ви тут. Ми поставили каву.' },
    journal: { eyebrow: 'Журнал · випуск без номера', title: 'Трохи більше\nчасу за столом.', intro: 'Нотатки про людей, масло й маленькі ритуали, що роблять ранок нашим.', article: 'Читати', empty: 'Невдовзі тут з’явиться нова історія.' },
    order: { eyebrow: 'З печі — до вас', title: 'Зберемо вам\nщось добре.', location: '1. Оберіть місце', mode: '2. Як забираєте?', pickup: 'Забрати самому', delivery: 'Доставка', menu: '3. Додайте до пакунка', cart: 'Ваш пакунок', empty: 'Виберіть щось із меню — ми зачекаємо.', checkout: 'Ваші контакти', name: 'Ім’я', phone: 'Телефон', email: 'Електронна пошта', pay: 'Підтвердити замовлення', paymentNote: 'Оплата тут поки демонстраційна. Підключення платіжного сервісу заплановано перед запуском.', success: 'Замовлення записали в наш блокнот!', successText: 'Це демо-підтвердження — жодної оплати не списано. Ми вже уявили, як пахне ваш пакунок.' },
    reserve: { eyebrow: 'Місце біля вікна чекає', title: 'Залишимо вам\nстолик?', intro: 'Напишіть нам кілька деталей — і ми притримаємо для вас місце. Поки що підтвердження з’явиться просто тут.', location: 'Кафе', date: 'Дата', time: 'Час', guests: 'Гостей', name: 'Як до вас звертатись?', email: 'Електронна пошта', phone: 'Телефон', note: 'Особливе побажання', submit: 'Попросити столик', success: 'Ми записали ваше побажання.', successText: 'Це поки що макет форми без надсилання на сервер. До зустрічі за столиком!' },
    contact: { eyebrow: 'Ми на зв’язку', title: 'Лишіть записку\nна кухонному столі.', intro: 'Для привітань, запитань про торти, співпраці або просто доброго слова.', name: 'Ваше ім’я', email: 'Електронна пошта', topic: 'Про що поговоримо?', message: 'Ваше повідомлення', send: 'Надіслати записку', success: 'Дякуємо за листа. Ми вже поставили його біля чайника.', inquiries: 'Преса, гурт і співпраця', inquiriesText: 'Для історій про випічку, гуртових замовлень та інших теплих ідей напишіть нам на hello@lepetitvoeu.example.', newsletter: 'Кілька теплих рядків раз на місяць', subscribe: 'Підписатися', socials: 'Зазирніть до нас' },
    footer: { line: 'Маленька пекарня великих ранків.', note: 'З борошном на фартусі та теплом у пакунку.', newsletter: 'Листи з печі', newsletterText: 'Один затишний лист на місяць. Обіцяємо без зайвого цукру.', email: 'Ваша електронна пошта', subscribe: 'Записатись', thanks: 'Ви у списку. До наступного ранку!', legal: 'Усі матеріали сайту та деталі локацій — демонстраційні.' },
  },
  en: {
    nav: { home: 'Home', menu: 'Menu', places: 'Locations', story: 'Our story', journal: 'Journal', contact: 'Contact', order: 'Order', reserve: 'Book a table' },
    common: { since: 'Made with love since 2016', handmade: 'Made by hand, never in a hurry', viewAll: 'See all', read: 'Read the story', from: 'from', add: 'Add', added: 'Added', address: 'Address', hours: 'Hours', cafe: 'Café', counter: 'To go', reserve: 'Reserve', order: 'Order', all: 'All', ukraine: 'Ukraine', poland: 'Poland', france: 'France', back: 'Back', total: 'Total', cart: 'Your basket', empty: 'For now, it only smells like a plan.', close: 'Close', placeholder: 'Demo details for this mock-up. Please verify addresses before launch.' },
    home: { eyebrow: 'A little bakery for little wishes · Lviv, since 2016', title: 'Some mornings\nare made for\none more warm croissant.', intro: 'We believe good things take their time. The dough rests, butter settles between its layers, and the city wakes up slowly.', story: 'How our story began', discover: 'Explore the menu', featured: 'Worth waking\nup for', note: 'Unfold your napkin. Morning is here.', locationsTitle: 'A little closer than you think', locationsText: 'From a small Lviv bakery to tables in Paris and Warsaw, we save a little room for a slower morning in every city.', journalTitle: 'Notes from our kitchen', journalText: 'Stories, scents and recipes we can’t help sharing.', quote: '“The secret isn’t speed. It’s one more layer of butter.”', quoteBy: 'From our founder’s notebook', cta: 'Find your morning table' },
    menu: { eyebrow: 'Straight from our oven · every morning', title: 'All the good things\nbetween the layers.', intro: 'Laminated dough loves patience. We give it the whole night, and you a reason to take your time choosing.', classics: 'Butter-kissed classics', filled: 'A little more filling', savory: 'A savoury morning', small: 'Alongside your croissant', note: 'Small batches. When we run out, tomorrow will be fresh.', orderNote: 'Online ordering is a demo; payment is not connected yet.' },
    places: { eyebrow: 'Stop by for a moment or stay awhile', title: 'We’ve already\nset the napkins.', intro: 'Fourteen places to pause for coffee and something warm from the oven. Some are a little takeaway window; others are a slow breakfast at the table.', cafe: 'Cafés with tables', counter: 'Bakery counters', filter: 'Browse by country', map: 'Our cities', reserveNote: 'Table reservations are available at cafés only.' },
    about: { eyebrow: 'Notre histoire · our story', title: 'One recipe.\nA whole string of mornings.', intro: 'It began with a recipe tucked into an apron pocket on the way home. From Paris to a kitchen in Lviv, where we learned to let dough take its time.', quote: '“Mama said: if there’s time for one more fold, it means we need it.”', storyTitle: 'The pocket-sized recipe', p1: 'In 2016, our family story smelled like butter slowly melting into flour. A recipe came home from a Parisian apprenticeship: a little creased, written in pencil, and already unmistakably ours.', p2: 'We opened our first bakery in Lviv. At dawn we rolled dough; by lunch we were learning the names of people coming back for another croissant. Cities have changed since then, but not that morning ritual.', p3: 'Now we have fourteen doors in three countries, from little takeaway windows to cafés where breakfast can linger. The figures and addresses here are placeholders; the recipe still begins with patience.', timelineTitle: 'Pages of the calendar', t1: 'A recipe comes home from Paris', t2: 'Our first bakery opens in Lviv', t3: 'Our mornings arrive in Warsaw', t4: 'A few more tables, now in Paris', end: 'Thank you for being here. We’ve put the coffee on.' },
    journal: { eyebrow: 'Journal · an unnumbered issue', title: 'A little more\ntime at the table.', intro: 'Notes on people, butter and the little rituals that make a morning ours.', article: 'Read story', empty: 'A new story will find its way here soon.' },
    order: { eyebrow: 'From our oven to you', title: 'Let’s put together\nsomething lovely.', location: '1. Choose a location', mode: '2. How will you get it?', pickup: 'Pick up', delivery: 'Delivery', menu: '3. Add to your bag', cart: 'Your bag', empty: 'Choose something from the menu; we’ll wait.', checkout: 'Your details', name: 'Name', phone: 'Phone', email: 'Email', pay: 'Place your order', paymentNote: 'Payment is a placeholder. A provider will be integrated before launch.', success: 'We’ve written your order in our notebook!', successText: 'This is a demo confirmation; no payment was taken.' },
    reserve: { eyebrow: 'A window-side seat is waiting', title: 'Shall we save\nyou a table?', intro: 'Share a few details and we’ll hold a little space for you. For now, your confirmation will appear here.', location: 'Café', date: 'Date', time: 'Time', guests: 'Guests', name: 'What should we call you?', email: 'Email', phone: 'Phone', note: 'A little note', submit: 'Ask for a table', success: 'We’ve noted your request.', successText: 'This form is a demo and isn’t connected to a server yet. See you at the table!' },
    contact: { eyebrow: 'We’re right here', title: 'Leave a note\non the kitchen table.', intro: 'For hellos, cake questions, collaborations or just a kind word.', name: 'Your name', email: 'Email', topic: 'What shall we talk about?', message: 'Your message', send: 'Send a little note', success: 'Thanks for your note. We’ve left it by the kettle.', inquiries: 'Press, wholesale & kindred ideas', inquiriesText: 'For stories about pastry and wholesale orders, write to hello@lepetitvoeu.example.', newsletter: 'A few warm words, once a month', subscribe: 'Subscribe', socials: 'Come say hello' },
    footer: { line: 'A little bakery for big mornings.', note: 'Flour on our aprons, warmth in every bag.', newsletter: 'Notes from the oven', newsletterText: 'One lovely letter each month. Nothing too sweet.', email: 'Your email address', subscribe: 'Sign me up', thanks: 'You’re on the list. Until next morning!', legal: 'All site content and location details are demonstration placeholders.' },
  },
  fr: {
    nav: { home: 'Accueil', menu: 'La carte', places: 'Adresses', story: 'Notre histoire', journal: 'Le journal', contact: 'Contact', order: 'Commander', reserve: 'Réserver' },
    common: { since: 'Fait avec amour depuis 2016', handmade: 'Fait main, sans se presser', viewAll: 'Tout voir', read: 'Lire le récit', from: 'dès', add: 'Ajouter', added: 'Ajouté', address: 'Adresse', hours: 'Horaires', cafe: 'Café', counter: 'À emporter', reserve: 'Réserver', order: 'Commander', all: 'Tout', ukraine: 'Ukraine', poland: 'Pologne', france: 'France', back: 'Retour', total: 'Total', cart: 'Votre panier', empty: 'Pour l’instant, il sent bon les projets.', close: 'Fermer', placeholder: 'Détails de démonstration. Merci de vérifier les adresses avant le lancement.' },
    home: { eyebrow: 'Une petite boulangerie · Lviv, depuis 2016', title: 'Certains matins\nsont faits pour\nun croissant encore chaud.', intro: 'Nous croyons que les bonnes choses prennent leur temps. La pâte repose, le beurre se glisse entre les couches, et la ville se réveille doucement.', story: 'Voici notre histoire', discover: 'Découvrir la carte', featured: 'De quoi se lever\nde bonne heure', note: 'Dépliez votre serviette. Le matin est là.', locationsTitle: 'Un peu plus près qu’on ne croit', locationsText: 'D’une petite boulangerie à Lviv aux tables de Paris et Varsovie, nous gardons une place pour les matins tranquilles.', journalTitle: 'Notes de notre cuisine', journalText: 'Des histoires, des parfums et des recettes à partager.', quote: '« Le secret, ce n’est pas la vitesse. C’est encore une couche de beurre. »', quoteBy: 'Dans le carnet de notre fondatrice', cta: 'Trouver sa table du matin' },
    menu: { eyebrow: 'Sorti du four · chaque matin', title: 'Le meilleur se cache\nentre les couches.', intro: 'La pâte feuilletée aime la patience. Nous lui offrons la nuit entière, et à vous le temps de choisir.', classics: 'Les classiques au beurre', filled: 'Un peu plus de gourmandise', savory: 'Un matin salé', small: 'Pour accompagner', note: 'Petites fournées. Demain, tout sera frais.', orderNote: 'La commande est une démonstration, sans paiement.' },
    places: { eyebrow: 'Passez un instant ou restez', title: 'Les serviettes\nsont déjà posées.', intro: 'Quatorze adresses pour une pause café et une viennoiserie chaude. Certaines ne sont qu’un comptoir, d’autres invitent à un petit-déjeuner qui prend son temps.', cafe: 'Cafés avec tables', counter: 'Comptoirs à emporter', filter: 'Parcourir par pays', map: 'Nos villes', reserveNote: 'La réservation est disponible uniquement dans les cafés.' },
    about: { eyebrow: 'Notre histoire · наша історія', title: 'Une recette.\nToute une suite de matins.', intro: 'Tout a commencé avec une recette rentrée dans une poche de tablier. De Paris à une cuisine de Lviv, où nous avons appris à attendre la pâte.', quote: '« Maman disait : s’il reste du temps pour un tour, c’est qu’il le faut. »', storyTitle: 'La recette de poche', p1: 'En 2016, notre histoire de famille sentait le beurre qui fond doucement dans la farine. Une recette est revenue d’un apprentissage parisien, un peu froissée, notée au crayon et déjà bien à nous.', p2: 'Nous avons ouvert notre première boulangerie à Lviv. À l’aube, nous étalions la pâte ; à midi, nous apprenions le prénom de ceux qui revenaient pour un autre croissant.', p3: 'Nous avons aujourd’hui quatorze portes dans trois pays. Les chiffres et adresses de cette maquette restent à confirmer ; la recette commence toujours par la patience.', timelineTitle: 'Quelques pages du calendrier', t1: 'Une recette revient de Paris', t2: 'Notre première boulangerie ouvre à Lviv', t3: 'Nos matins arrivent à Varsovie', t4: 'Quelques tables de plus à Paris', end: 'Merci d’être là. Le café est prêt.' },
    journal: { eyebrow: 'Le journal · un numéro sans numéro', title: 'Un peu plus\nde temps à table.', intro: 'Des notes sur les gens, le beurre et ces petits rituels du matin.', article: 'Lire le récit', empty: 'Une nouvelle histoire arrivera bientôt.' },
    order: { eyebrow: 'Du four à chez vous', title: 'Préparons\nquelque chose de bon.', location: '1. Choisir une adresse', mode: '2. Comment le recevoir ?', pickup: 'À emporter', delivery: 'Livraison', menu: '3. Ajouter au panier', cart: 'Votre panier', empty: 'Choisissez quelque chose, nous attendons.', checkout: 'Vos coordonnées', name: 'Nom', phone: 'Téléphone', email: 'E-mail', pay: 'Confirmer la commande', paymentNote: 'Le paiement est une maquette. Un prestataire sera ajouté avant le lancement.', success: 'Votre commande est dans notre carnet !', successText: 'Ceci est une confirmation de démonstration. Aucun paiement n’a été effectué.' },
    reserve: { eyebrow: 'Une place près de la fenêtre vous attend', title: 'On vous garde\nune table ?', intro: 'Quelques détails et nous vous gardons une petite place. Pour le moment, la confirmation apparaîtra ici.', location: 'Café', date: 'Date', time: 'Heure', guests: 'Personnes', name: 'Comment vous appelez-vous ?', email: 'E-mail', phone: 'Téléphone', note: 'Un petit mot', submit: 'Demander une table', success: 'Votre demande est notée.', successText: 'Ce formulaire de démonstration n’est pas encore relié à un serveur. À bientôt !' },
    contact: { eyebrow: 'Nous sommes là', title: 'Laissez un mot\nsur la table de cuisine.', intro: 'Pour un bonjour, une question sur les gâteaux ou une idée à partager.', name: 'Votre nom', email: 'E-mail', topic: 'De quoi parler ?', message: 'Votre message', send: 'Envoyer un mot', success: 'Merci pour votre mot, il est près de la bouilloire.', inquiries: 'Presse, commandes & jolies idées', inquiriesText: 'Pour parler de viennoiseries et de commandes en gros : hello@lepetitvoeu.example.', newsletter: 'Quelques mots doux, une fois par mois', subscribe: 'S’inscrire', socials: 'Venez nous voir' },
    footer: { line: 'Une petite boulangerie pour les grands matins.', note: 'De la farine sur le tablier, de la chaleur dans le sac.', newsletter: 'Des nouvelles du four', newsletterText: 'Une jolie lettre par mois, pas plus sucrée qu’il ne faut.', email: 'Votre adresse e-mail', subscribe: 'Je m’inscris', thanks: 'Vous êtes sur la liste. À bientôt !', legal: 'Les textes et adresses du site sont des éléments de démonstration.' },
  },
}

const sharedCopy = {
  'common.minutes': { uk: 'хв читання', en: 'min read', fr: 'min de lecture' },
  'common.quantity': { uk: 'Кількість', en: 'Quantity', fr: 'Quantité' },
}

export function t(language, path) {
  return path.split('.').reduce((value, part) => value?.[part], copy[language]) ?? sharedCopy[path]?.[language] ?? path
}